### PR TITLE
Fixed sponsor logos and added sponsorship agreement.

### PR DESCRIPTION
**Pull request by Axiematic**
Hi Jon,

I have added the Toptal logo, set all the logos aspect 1:4 and added the sponsor agreement.

### CODE REVIEW

**Comment by jonmcalder** [comment]
Hi @EmmaCollier! This looks great - are you able to resolve the conflicts so that I can merge?

**Comment by datawookie** [comment]
Hi @jonmcalder and @EmmaCollier, I quickly resolved the merge conflict and accepted. Changes should now be live. @EmmaCollier please check the site.

**Comment by Axiematic** [comment]
Thank you for resolving those conflicts @DataWookie ! I just checked them now, all seems in order.

**Comment by jonmcalder** [comment]
@DataWookie You resolved the merge conflict but you reverted @EmmaCollier's changes to the UCT logo in the process. Fixed in https://github.com/satRdays/capetown2018/pull/5.

**Pull request merged**
